INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD)
VALUES ('MIKE', '1111');
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD)
VALUES ('TOM', '1111');
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD)
VALUES ('LIANA', '2222');
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD)
VALUES ('JHON', '2222');

INSERT INTO CAR_RENTAL.AUTHORITY (USERNAME, AUTHORITY)
VALUES ('MIKE', 'ADMIN');
INSERT INTO CAR_RENTAL.AUTHORITY (USERNAME, AUTHORITY)
VALUES ('TOM', 'ADMIN');
INSERT INTO CAR_RENTAL.AUTHORITY (USERNAME, AUTHORITY)
VALUES ('LIANA', 'CLIENT');
INSERT INTO CAR_RENTAL.AUTHORITY (USERNAME, AUTHORITY)
VALUES ('JHON', 'CLIENT');

INSERT INTO CAR_RENTAL.USER_DETAILS (USERNAME, EMAIL)
VALUES ('MIKE', 'MIKE@GOOGLE.COM');
INSERT INTO CAR_RENTAL.USER_DETAILS (USERNAME, EMAIL)
VALUES ('TOM', 'TOM@GOOGLE.COM');
INSERT INTO CAR_RENTAL.USER_DETAILS (USERNAME, EMAIL)
VALUES ('LIANA', 'LIANA@GOOGLE.COM');
INSERT INTO CAR_RENTAL.USER_DETAILS (USERNAME, EMAIL)
VALUES ('JHON', 'JHON@GOOGLE.COM');

INSERT INTO CAR_RENTAL.DISCOUNT_STATUS (STATUS, DISCOUNT)
VALUES ('BRONZE', 3.0);
INSERT INTO CAR_RENTAL.DISCOUNT_STATUS (STATUS, DISCOUNT)
VALUES ('SILVER', 5.0);
INSERT INTO CAR_RENTAL.DISCOUNT_STATUS (STATUS, DISCOUNT)
VALUES ('GOLD', 10.0);
INSERT INTO CAR_RENTAL.DISCOUNT_STATUS (STATUS, DISCOUNT)
VALUES ('BRILLIANT', 15.0);

INSERT INTO CAR_RENTAL.CAR_STATUS (STATUS)
VALUES ('READY');
INSERT INTO CAR_RENTAL.CAR_STATUS (STATUS)
VALUES ('BROKEN');
INSERT INTO CAR_RENTAL.CAR_STATUS (STATUS)
VALUES ('REPAIRING');

INSERT INTO CAR_RENTAL.ORDER_STATUS (STATUS, DESCRIPTION)
VALUES ('WAITING FOR PAYMENT', 'ORDER IS WAITING FOR CLIENT''S PAYMENT.');
INSERT INTO CAR_RENTAL.ORDER_STATUS (STATUS, DESCRIPTION)
VALUES ('PAID', 'ORDER IS PAID AND WAITING FOR CONFIRMATION.');
INSERT INTO CAR_RENTAL.ORDER_STATUS (STATUS, DESCRIPTION)
VALUES ('CONFIRMED', 'ORDER IS CONFIRMED. CAR IS READY.');
INSERT INTO CAR_RENTAL.ORDER_STATUS (STATUS, DESCRIPTION)
VALUES ('COMPLETED', 'ORDER IS COMPLETED.');
INSERT INTO CAR_RENTAL.ORDER_STATUS (STATUS, DESCRIPTION)
VALUES ('DECLINED BY ADMIN', 'ORDER IS DECLINED BY ADMIN.');
INSERT INTO CAR_RENTAL.ORDER_STATUS (STATUS, DESCRIPTION)
VALUES ('CANCELED BY CLIENT', 'ORDER IS CANCELED BY CLIENT.');

INSERT INTO CAR_RENTAL.CAR_MODEL (BRAND_NAME, CAR_MODEL, BODY_TYPE, FUEL_TYPE, ENGINE_VOLUME, TRANSMISSION, BODY_COLOR,
                                  INTERIOR_COLOR)
VALUES ('VOLKSWAGEN', 'POLO', 'SEDAN', 'PETROL', 1.6, 'MANUAL TRANSMISSION', 'REEF BLUE', 'GRAY');
INSERT INTO CAR_RENTAL.CAR_MODEL (BRAND_NAME, CAR_MODEL, BODY_TYPE, FUEL_TYPE, ENGINE_VOLUME, TRANSMISSION, BODY_COLOR,
                                  INTERIOR_COLOR)
VALUES ('VOLKSWAGEN', 'TAOS', 'CROSSOVER', 'PETROL', 2.0, 'AUTOMATIC TRANSMISSION', 'REEF BLUE', 'BLACK');
INSERT INTO CAR_RENTAL.CAR_MODEL (BRAND_NAME, CAR_MODEL, BODY_TYPE, FUEL_TYPE, ENGINE_VOLUME, TRANSMISSION, BODY_COLOR,
                                  INTERIOR_COLOR)
VALUES ('VOLKSWAGEN', 'TIGUAN', 'CROSSOVER', 'PETROL', 2.0, 'AUTOMATIC TRANSMISSION', 'SILK BLUE METALLIC', 'TAN');
INSERT INTO CAR_RENTAL.CAR_MODEL (BRAND_NAME, CAR_MODEL, BODY_TYPE, FUEL_TYPE, ENGINE_VOLUME, TRANSMISSION, BODY_COLOR,
                                  INTERIOR_COLOR)
VALUES ('NISSAN', 'JUKE', 'SUV', 'PETROL', 1.6, 'MANUAL TRANSMISSION', 'RED', 'BLACK');
INSERT INTO CAR_RENTAL.CAR_MODEL (BRAND_NAME, CAR_MODEL, BODY_TYPE, FUEL_TYPE, ENGINE_VOLUME, TRANSMISSION, BODY_COLOR,
                                  INTERIOR_COLOR)
VALUES ('NISSAN', 'X-TRAIL', 'CROSSOVER', 'DIESEL', 1.6, 'AUTOMATIC TRANSMISSION', 'RED', 'TAN');

INSERT INTO CAR_RENTAL.CAR (STATE_NUMBER, CAR_MODEL_ID, CAR_STATUS_ID)
VALUES ('2911CC-7', 1, 1);
INSERT INTO CAR_RENTAL.CAR (STATE_NUMBER, CAR_MODEL_ID, CAR_STATUS_ID)
VALUES ('2912CC-7', 1, 1);
INSERT INTO CAR_RENTAL.CAR (STATE_NUMBER, CAR_MODEL_ID, CAR_STATUS_ID)
VALUES ('2922CC-7', 2, 1);
INSERT INTO CAR_RENTAL.CAR (STATE_NUMBER, CAR_MODEL_ID, CAR_STATUS_ID)
VALUES ('2930CC-7', 3, 1);
INSERT INTO CAR_RENTAL.CAR (STATE_NUMBER, CAR_MODEL_ID, CAR_STATUS_ID)
VALUES ('4089CC-7', 4, 1);
INSERT INTO CAR_RENTAL.CAR (STATE_NUMBER, CAR_MODEL_ID, CAR_STATUS_ID)
VALUES ('4054CC-7', 5, 1);