### login
POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

username=user2&password=11111111

### logout
POST http://localhost:8080/logout
Content-Type: application/x-www-form-urlencoded

### GET all cars with default pageble values (size=3, page=0)
GET http://localhost:8080/api/cars
Accept: application/json

### GET all cars with pageble values in the following paramethers: size=4, page=1
GET http://localhost:8080/api/cars?size=4&page=1
Accept: application/json

### GET car with id=1
GET http://localhost:8080/api/cars/1
Accept: application/json

### GET car with id=7 (Exception expected)
GET http://localhost:8080/api/cars/7
Accept: application/json

### Update car status with id=1
PUT http://localhost:8080/api/cars/1
Content-Type: application/json

{
  "stateNumber": "1234TX-7"
}

### Update car status with id=1 (Exception expected cause has no field "stateNumber")
PUT http://localhost:8080/api/cars/1
Content-Type: application/json

{
  "st": "1234TX-7"
}