INSERT INTO CAR_RENTAL.USER_ROLE (ROLE)
VALUES ('ADMIN');
INSERT INTO CAR_RENTAL.USER_ROLE (ROLE)
VALUES ('CLIENT');

INSERT INTO CAR_RENTAL.DISCOUNT_STATUS (STATUS, DISCOUNT)
VALUES ('BRONZE', 3.0);
INSERT INTO CAR_RENTAL.DISCOUNT_STATUS (STATUS, DISCOUNT)
VALUES ('SILVER', 5.0);
INSERT INTO CAR_RENTAL.DISCOUNT_STATUS (STATUS, DISCOUNT)
VALUES ('GOLD', 10.0);
INSERT INTO CAR_RENTAL.DISCOUNT_STATUS (STATUS, DISCOUNT)
VALUES ('BRILLIANT', 15.0);

INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER1', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER2', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER3', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);

INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('MIKE', '$2a$12$aD3zBkGlAtwAHmcUravf2eUPokVFchcA0JlDQN.89lEE9AWxcAq0C', 'mike@google.com', 1, 1);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('TOM', '$2a$12$oatgfJyZKzY3TkBhD0riHeyQsREkeSBiKe7idkb4DL9JBF6oh63PS', 'tom@google.com', 1, 2);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('LIANA', '$2a$12$z7BYvMAHz9COF39c6pthc.cbBqtg.BR2TAEWH4.trEC8QK0XoCDMy', 'liana@google.com', 2, 3);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('JHON', '$2a$12$GFZXMACDCVELfF9Uyy1sdOQJ2xgeoyMtKR/1uLp8qI9xhGn819Cgi', 'jhon@google.com', 2, 4);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('HANNA', '$2a$12$z7BYvMAHz9COF39c6pthc.cbBqtg.BR2TAEWH4.trEC8QK0XoCDMy', 'hanna@google.com', 2, 5);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('MARY', '$2a$12$GFZXMACDCVELfF9Uyy1sdOQJ2xgeoyMtKR/1uLp8qI9xhGn819Cgi', 'mary@google.com', 2, 6);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('LIZ', '$2a$12$z7BYvMAHz9COF39c6pthc.cbBqtg.BR2TAEWH4.trEC8QK0XoCDMy', 'liz@google.com', 2, 7);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('ROBERT', '$2a$12$GFZXMACDCVELfF9Uyy1sdOQJ2xgeoyMtKR/1uLp8qI9xhGn819Cgi', 'robert@google.com', 2, 8);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('RON', '$2a$12$z7BYvMAHz9COF39c6pthc.cbBqtg.BR2TAEWH4.trEC8QK0XoCDMy', 'ron@google.com', 2, 9);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('BOB', '$2a$12$GFZXMACDCVELfF9Uyy1sdOQJ2xgeoyMtKR/1uLp8qI9xhGn819Cgi', 'bob@google.com', 2, 10);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('SARA', '$2a$12$z7BYvMAHz9COF39c6pthc.cbBqtg.BR2TAEWH4.trEC8QK0XoCDMy', 'sara@google.com', 2, 11);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('LI', '$2a$12$GFZXMACDCVELfF9Uyy1sdOQJ2xgeoyMtKR/1uLp8qI9xhGn819Cgi', 'li@google.com', 2, 12);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('LIA', '$2a$12$z7BYvMAHz9COF39c6pthc.cbBqtg.BR2TAEWH4.trEC8QK0XoCDMy', 'lia@google.com', 2, 13);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('BOBBY', '$2a$12$GFZXMACDCVELfF9Uyy1sdOQJ2xgeoyMtKR/1uLp8qI9xhGn819Cgi', 'bobby@google.com', 2, 14);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('HO', '$2a$12$z7BYvMAHz9COF39c6pthc.cbBqtg.BR2TAEWH4.trEC8QK0XoCDMy', 'ho@google.com', 2, 15);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('FREDDY', '$2a$12$GFZXMACDCVELfF9Uyy1sdOQJ2xgeoyMtKR/1uLp8qI9xhGn819Cgi', 'freddy@google.com', 2, 16);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('GREG', '$2a$12$z7BYvMAHz9COF39c6pthc.cbBqtg.BR2TAEWH4.trEC8QK0XoCDMy', 'greg@google.com', 2, 17);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('ANTONY', '$2a$12$GFZXMACDCVELfF9Uyy1sdOQJ2xgeoyMtKR/1uLp8qI9xhGn819Cgi', 'antony@google.com', 2, 18);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('CRIS', '$2a$12$z7BYvMAHz9COF39c6pthc.cbBqtg.BR2TAEWH4.trEC8QK0XoCDMy', 'cris@google.com', 2, 19);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('MARTIN', '$2a$12$GFZXMACDCVELfF9Uyy1sdOQJ2xgeoyMtKR/1uLp8qI9xhGn819Cgi', 'martin@google.com', 2, 20);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('MARGARET', '$2a$12$z7BYvMAHz9COF39c6pthc.cbBqtg.BR2TAEWH4.trEC8QK0XoCDMy', 'margaret@google.com', 2, 21);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('STIVE', '$2a$12$GFZXMACDCVELfF9Uyy1sdOQJ2xgeoyMtKR/1uLp8qI9xhGn819Cgi', 'stive@google.com', 2, 22);

INSERT INTO CAR_RENTAL.CAR_STATUS (STATUS)
VALUES ('READY');
INSERT INTO CAR_RENTAL.CAR_STATUS (STATUS)
VALUES ('BROKEN');
INSERT INTO CAR_RENTAL.CAR_STATUS (STATUS)
VALUES ('REPAIRING');

INSERT INTO CAR_RENTAL.ORDER_STATUS (STATUS, DESCRIPTION)
VALUES ('WAITING FOR PAYMENT', 'ORDER IS WAITING FOR CLIENT''S PAYMENT.');
INSERT INTO CAR_RENTAL.ORDER_STATUS (STATUS, DESCRIPTION)
VALUES ('PAID', 'ORDER IS PAID AND WAITING FOR CONFIRMATION.');
INSERT INTO CAR_RENTAL.ORDER_STATUS (STATUS, DESCRIPTION)
VALUES ('CONFIRMED', 'ORDER IS CONFIRMED. CAR IS READY.');
INSERT INTO CAR_RENTAL.ORDER_STATUS (STATUS, DESCRIPTION)
VALUES ('COMPLETED', 'ORDER IS COMPLETED.');
INSERT INTO CAR_RENTAL.ORDER_STATUS (STATUS, DESCRIPTION)
VALUES ('DECLINED BY ADMIN', 'ORDER IS DECLINED BY ADMIN.');
INSERT INTO CAR_RENTAL.ORDER_STATUS (STATUS, DESCRIPTION)
VALUES ('CANCELED BY CLIENT', 'ORDER IS CANCELED BY CLIENT.');

INSERT INTO CAR_RENTAL.CAR_MODEL (BRAND_NAME, MODEL, BODY_TYPE, FUEL_TYPE, ENGINE_VOLUME, TRANSMISSION, BODY_COLOR,
                                  INTERIOR_COLOR, PRICE_PER_MINUTE)
VALUES ('VOLKSWAGEN', 'POLO', 'SEDAN', 'PETROL', 1.6, 'MANUAL TRANSMISSION', 'REEF BLUE', 'GRAY', 8);
INSERT INTO CAR_RENTAL.CAR_MODEL (BRAND_NAME, MODEL, BODY_TYPE, FUEL_TYPE, ENGINE_VOLUME, TRANSMISSION, BODY_COLOR,
                                  INTERIOR_COLOR, PRICE_PER_MINUTE)
VALUES ('VOLKSWAGEN', 'TAOS', 'CROSSOVER', 'PETROL', 2.0, 'AUTOMATIC TRANSMISSION', 'REEF BLUE', 'BLACK', 15);
INSERT INTO CAR_RENTAL.CAR_MODEL (BRAND_NAME, MODEL, BODY_TYPE, FUEL_TYPE, ENGINE_VOLUME, TRANSMISSION, BODY_COLOR,
                                  INTERIOR_COLOR, PRICE_PER_MINUTE)
VALUES ('VOLKSWAGEN', 'TIGUAN', 'CROSSOVER', 'PETROL', 2.0, 'AUTOMATIC TRANSMISSION', 'SILK BLUE METALLIC', 'TAN',
        18);
INSERT INTO CAR_RENTAL.CAR_MODEL (BRAND_NAME, MODEL, BODY_TYPE, FUEL_TYPE, ENGINE_VOLUME, TRANSMISSION, BODY_COLOR,
                                  INTERIOR_COLOR, PRICE_PER_MINUTE)
VALUES ('NISSAN', 'JUKE', 'SUV', 'PETROL', 1.6, 'MANUAL TRANSMISSION', 'RED', 'BLACK', 11);
INSERT INTO CAR_RENTAL.CAR_MODEL (BRAND_NAME, MODEL, BODY_TYPE, FUEL_TYPE, ENGINE_VOLUME, TRANSMISSION, BODY_COLOR,
                                  INTERIOR_COLOR, PRICE_PER_MINUTE)
VALUES ('NISSAN', 'X-TRAIL', 'CROSSOVER', 'DIESEL', 1.6, 'AUTOMATIC TRANSMISSION', 'RED', 'TAN', 19);

INSERT INTO CAR_RENTAL.CAR (STATE_NUMBER, CAR_MODEL_ID, CAR_STATUS_ID)
VALUES ('2911CC-7', 1, 1);
INSERT INTO CAR_RENTAL.CAR (STATE_NUMBER, CAR_MODEL_ID, CAR_STATUS_ID)
VALUES ('2912CC-7', 1, 1);
INSERT INTO CAR_RENTAL.CAR (STATE_NUMBER, CAR_MODEL_ID, CAR_STATUS_ID)
VALUES ('2922CC-7', 2, 1);
INSERT INTO CAR_RENTAL.CAR (STATE_NUMBER, CAR_MODEL_ID, CAR_STATUS_ID)
VALUES ('2930CC-7', 3, 1);
INSERT INTO CAR_RENTAL.CAR (STATE_NUMBER, CAR_MODEL_ID, CAR_STATUS_ID)
VALUES ('4089CC-7', 4, 1);
INSERT INTO CAR_RENTAL.CAR (STATE_NUMBER, CAR_MODEL_ID, CAR_STATUS_ID)
VALUES ('4054CC-7', 5, 1);