--liquibase formatted sql
--changeset katsiaryna.silina@gmail.com:add-car-table splitStatements:true endDelimiter:;
CREATE TABLE CAR_RENTAL.CAR
(
    ID            INT AUTO_INCREMENT PRIMARY KEY,
    STATE_NUMBER  VARCHAR(10) NOT NULL,
    CAR_MODEL_ID  INT         NOT NULL,
    CAR_STATUS_ID INT         NOT NULL,
    CONSTRAINT FK_CAR_CAR_MODEL FOREIGN KEY (CAR_MODEL_ID) REFERENCES CAR_RENTAL.CAR_MODEL (ID),
    CONSTRAINT FK_CAR_CAR_STATUS FOREIGN KEY (CAR_STATUS_ID) REFERENCES CAR_RENTAL.CAR_STATUS (ID)
);

CREATE INDEX IDX_CAR_STATE_NUMBER ON CAR_RENTAL.CAR (STATE_NUMBER);
CREATE INDEX IDX_CAR_CAR_MODEL_ID ON CAR_RENTAL.CAR (CAR_MODEL_ID);
CREATE INDEX IDX_CAR_CAR_STATUS_ID ON CAR_RENTAL.CAR (CAR_STATUS_ID);
--rollback DROP TABLE IF EXISTS CAR_RENTAL.CAR