--liquibase formatted sql
--changeset katsiaryna.silina@gmail.com:add-order-table splitStatements:true endDelimiter:;
CREATE TABLE CAR_RENTAL.ORDER
(
    ID                  INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_DATE          DATETIME NOT NULL DEFAULT NOW(),
    USER_ID             INT      NOT NULL,
    DATE_FROM           DATETIME NOT NULL,
    DATE_TO             DATETIME NOT NULL,
    CAR_MODEL_ID        INT      NOT NULL,
    CAR_ID              INT,
    PRICE_WITH_DISCOUNT DOUBLE   NOT NULL,
    DISCOUNT            DOUBLE   NOT NULL DEFAULT 0,
    DECLINE_REASON      VARCHAR(300),
    ORDER_STATUS_ID     INT      NOT NULL DEFAULT 1,
    CONSTRAINT CHECK_ORDER_DISCOUNT CHECK (DISCOUNT BETWEEN 0.0 AND 100.0),
    CONSTRAINT FK_ORDER_CAR_MODEL FOREIGN KEY (CAR_MODEL_ID) REFERENCES CAR_RENTAL.CAR_MODEL (ID),
    CONSTRAINT FK_ORDER_CAR FOREIGN KEY (CAR_ID) REFERENCES CAR_RENTAL.CAR (ID),
    CONSTRAINT FK_ORDER_ORDER_STATUS FOREIGN KEY (ORDER_STATUS_ID) REFERENCES CAR_RENTAL.ORDER_STATUS (ID),
    CONSTRAINT FK_ORDER_USER FOREIGN KEY (USER_ID) REFERENCES CAR_RENTAL.USER (ID)
);

CREATE INDEX IDX_ORDER_CAR_MODEL_ID ON CAR_RENTAL.ORDER (CAR_MODEL_ID);
CREATE INDEX IDX_ORDER_CAR_ID ON CAR_RENTAL.ORDER (CAR_ID);
CREATE INDEX IDX_ORDER_USER_ID ON CAR_RENTAL.ORDER (USER_ID);
CREATE INDEX IDX_ORDER_ORDER_STATUS_ID ON CAR_RENTAL.ORDER (ORDER_STATUS_ID);
CREATE INDEX IDX_ORDER_DATE_STAT ON CAR_RENTAL.ORDER ((DATE (ORDER_DATE)), ORDER_STATUS_ID);
CREATE INDEX IDX_ORDER_DATE_FR_TO ON CAR_RENTAL.ORDER (DATE_FROM, DATE_TO);
--rollback DROP TABLE IF EXISTS CAR_RENTAL.ORDER