--liquibase formatted sql
--changeset katsiaryna.silina@gmail.com:populate-discount-status-table splitStatements:true endDelimiter:;
INSERT INTO CAR_RENTAL.DISCOUNT_STATUS (STATUS, DISCOUNT)
VALUES ('BRONZE', 3.0);
INSERT INTO CAR_RENTAL.DISCOUNT_STATUS (STATUS, DISCOUNT)
VALUES ('SILVER', 5.0);
INSERT INTO CAR_RENTAL.DISCOUNT_STATUS (STATUS, DISCOUNT)
VALUES ('GOLD', 10.0);
INSERT INTO CAR_RENTAL.DISCOUNT_STATUS (STATUS, DISCOUNT)
VALUES ('BRILLIANT', 15.0);