--liquibase formatted sql
--changeset katsiaryna.silina@gmail.com:populate-user-details-table splitStatements:true endDelimiter:;
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER1', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER2', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER3', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.USER_DETAILS(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);