--liquibase formatted sql
--changeset katsiaryna.silina@gmail.com:populate-user-table splitStatements:true endDelimiter:;
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('MIKE', '$2a$12$aD3zBkGlAtwAHmcUravf2eUPokVFchcA0JlDQN.89lEE9AWxcAq0C', 'mike@google.com', 1, 1);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('TOM', '$2a$12$oatgfJyZKzY3TkBhD0riHeyQsREkeSBiKe7idkb4DL9JBF6oh63PS', 'tom@google.com', 1, 2);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('LIANA', '$2a$12$z7BYvMAHz9COF39c6pthc.cbBqtg.BR2TAEWH4.trEC8QK0XoCDMy', 'liana@google.com', 2, 3);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('JHON', '$2a$12$GFZXMACDCVELfF9Uyy1sdOQJ2xgeoyMtKR/1uLp8qI9xhGn819Cgi', 'jhon@google.com', 2, 4);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('HANNA', '$2a$12$z7BYvMAHz9COF39c6pthc.cbBqtg.BR2TAEWH4.trEC8QK0XoCDMy', 'hanna@google.com', 2, 5);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('MARY', '$2a$12$GFZXMACDCVELfF9Uyy1sdOQJ2xgeoyMtKR/1uLp8qI9xhGn819Cgi', 'mary@google.com', 2, 6);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('LIZ', '$2a$12$z7BYvMAHz9COF39c6pthc.cbBqtg.BR2TAEWH4.trEC8QK0XoCDMy', 'liz@google.com', 2, 7);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('ROBERT', '$2a$12$GFZXMACDCVELfF9Uyy1sdOQJ2xgeoyMtKR/1uLp8qI9xhGn819Cgi', 'robert@google.com', 2, 8);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('RON', '$2a$12$z7BYvMAHz9COF39c6pthc.cbBqtg.BR2TAEWH4.trEC8QK0XoCDMy', 'ron@google.com', 2, 9);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('BOB', '$2a$12$GFZXMACDCVELfF9Uyy1sdOQJ2xgeoyMtKR/1uLp8qI9xhGn819Cgi', 'bob@google.com', 2, 10);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('SARA', '$2a$12$z7BYvMAHz9COF39c6pthc.cbBqtg.BR2TAEWH4.trEC8QK0XoCDMy', 'sara@google.com', 2, 11);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('LI', '$2a$12$GFZXMACDCVELfF9Uyy1sdOQJ2xgeoyMtKR/1uLp8qI9xhGn819Cgi', 'li@google.com', 2, 12);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('LIA', '$2a$12$z7BYvMAHz9COF39c6pthc.cbBqtg.BR2TAEWH4.trEC8QK0XoCDMy', 'lia@google.com', 2, 13);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('BOBBY', '$2a$12$GFZXMACDCVELfF9Uyy1sdOQJ2xgeoyMtKR/1uLp8qI9xhGn819Cgi', 'bobby@google.com', 2, 14);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('HO', '$2a$12$z7BYvMAHz9COF39c6pthc.cbBqtg.BR2TAEWH4.trEC8QK0XoCDMy', 'ho@google.com', 2, 15);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('FREDDY', '$2a$12$GFZXMACDCVELfF9Uyy1sdOQJ2xgeoyMtKR/1uLp8qI9xhGn819Cgi', 'freddy@google.com', 2, 16);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('GREG', '$2a$12$z7BYvMAHz9COF39c6pthc.cbBqtg.BR2TAEWH4.trEC8QK0XoCDMy', 'greg@google.com', 2, 17);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('ANTONY', '$2a$12$GFZXMACDCVELfF9Uyy1sdOQJ2xgeoyMtKR/1uLp8qI9xhGn819Cgi', 'antony@google.com', 2, 18);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('CRIS', '$2a$12$z7BYvMAHz9COF39c6pthc.cbBqtg.BR2TAEWH4.trEC8QK0XoCDMy', 'cris@google.com', 2, 19);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('MARTIN', '$2a$12$GFZXMACDCVELfF9Uyy1sdOQJ2xgeoyMtKR/1uLp8qI9xhGn819Cgi', 'martin@google.com', 2, 20);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('MARGARET', '$2a$12$z7BYvMAHz9COF39c6pthc.cbBqtg.BR2TAEWH4.trEC8QK0XoCDMy', 'margaret@google.com', 2, 21);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, ROLE_ID, USER_DETAILS_ID)
VALUES ('STIVE', '$2a$12$GFZXMACDCVELfF9Uyy1sdOQJ2xgeoyMtKR/1uLp8qI9xhGn819Cgi', 'stive@google.com', 2, 22);