--liquibase formatted sql
--changeset katsiaryna.silina@gmail.com:populate-order-status-table splitStatements:true endDelimiter:;
INSERT INTO CAR_RENTAL.ORDER_STATUS (STATUS, DESCRIPTION)
VALUES ('WAITING FOR PAYMENT', 'ORDER IS WAITING FOR CLIENT''S PAYMENT.');
INSERT INTO CAR_RENTAL.ORDER_STATUS (STATUS, DESCRIPTION)
VALUES ('PAID', 'ORDER IS PAID AND WAITING FOR CONFIRMATION.');
INSERT INTO CAR_RENTAL.ORDER_STATUS (STATUS, DESCRIPTION)
VALUES ('CONFIRMED', 'ORDER IS CONFIRMED. CAR IS READY.');
INSERT INTO CAR_RENTAL.ORDER_STATUS (STATUS, DESCRIPTION)
VALUES ('COMPLETED', 'ORDER IS COMPLETED.');
INSERT INTO CAR_RENTAL.ORDER_STATUS (STATUS, DESCRIPTION)
VALUES ('DECLINED BY ADMIN', 'ORDER IS DECLINED BY ADMIN.');
INSERT INTO CAR_RENTAL.ORDER_STATUS (STATUS, DESCRIPTION)
VALUES ('CANCELED BY CLIENT', 'ORDER IS CANCELED BY CLIENT.');