--liquibase formatted sql
--changeset katsiaryna.silina@gmail.com:populate-car-model-table splitStatements:true endDelimiter:;
INSERT INTO CAR_RENTAL.CAR_MODEL (BRAND_NAME, MODEL, BODY_TYPE, FUEL_TYPE, ENGINE_VOLUME, TRANSMISSION, BODY_COLOR,
                                  INTERIOR_COLOR, PRICE_PER_MINUTE)
VALUES ('VOLKSWAGEN', 'POLO', 'SEDAN', 'PETROL', 1.6, 'MANUAL TRANSMISSION', 'REEF BLUE', 'GRAY', 8);
INSERT INTO CAR_RENTAL.CAR_MODEL (BRAND_NAME, MODEL, BODY_TYPE, FUEL_TYPE, ENGINE_VOLUME, TRANSMISSION, BODY_COLOR,
                                  INTERIOR_COLOR, PRICE_PER_MINUTE)
VALUES ('VOLKSWAGEN', 'TAOS', 'CROSSOVER', 'PETROL', 2.0, 'AUTOMATIC TRANSMISSION', 'REEF BLUE', 'BLACK', 15);
INSERT INTO CAR_RENTAL.CAR_MODEL (BRAND_NAME, MODEL, BODY_TYPE, FUEL_TYPE, ENGINE_VOLUME, TRANSMISSION, BODY_COLOR,
                                  INTERIOR_COLOR, PRICE_PER_MINUTE)
VALUES ('VOLKSWAGEN', 'TIGUAN', 'CROSSOVER', 'PETROL', 2.0, 'AUTOMATIC TRANSMISSION', 'SILK BLUE METALLIC', 'TAN',
        18);
INSERT INTO CAR_RENTAL.CAR_MODEL (BRAND_NAME, MODEL, BODY_TYPE, FUEL_TYPE, ENGINE_VOLUME, TRANSMISSION, BODY_COLOR,
                                  INTERIOR_COLOR, PRICE_PER_MINUTE)
VALUES ('NISSAN', 'JUKE', 'SUV', 'PETROL', 1.6, 'MANUAL TRANSMISSION', 'RED', 'BLACK', 11);
INSERT INTO CAR_RENTAL.CAR_MODEL (BRAND_NAME, MODEL, BODY_TYPE, FUEL_TYPE, ENGINE_VOLUME, TRANSMISSION, BODY_COLOR,
                                  INTERIOR_COLOR, PRICE_PER_MINUTE)
VALUES ('NISSAN', 'X-TRAIL', 'CROSSOVER', 'DIESEL', 1.6, 'AUTOMATIC TRANSMISSION', 'RED', 'TAN', 19);
